// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6aGCMzyRfioB25p_yoskmv5aJWHv55UA',
    appId: '1:21933192505:web:a73ad14326a15326bc64e8',
    messagingSenderId: '21933192505',
    projectId: 'ctse-lab3',
    authDomain: 'ctse-lab3.firebaseapp.com',
    storageBucket: 'ctse-lab3.appspot.com',
    measurementId: 'G-GR19LPY3XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIUrOcXIdksxq_6bktev0yB8urMr6L078',
    appId: '1:21933192505:android:a23b01589c30a39cbc64e8',
    messagingSenderId: '21933192505',
    projectId: 'ctse-lab3',
    storageBucket: 'ctse-lab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxOQLme_QVwFcdHopUetIgK6wiP2XnyI',
    appId: '1:21933192505:ios:74757857e7e98308bc64e8',
    messagingSenderId: '21933192505',
    projectId: 'ctse-lab3',
    storageBucket: 'ctse-lab3.appspot.com',
    iosClientId: '21933192505-l9mdhcko0ivtmk4rp4ein2j4kmbb71aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseLab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxOQLme_QVwFcdHopUetIgK6wiP2XnyI',
    appId: '1:21933192505:ios:74757857e7e98308bc64e8',
    messagingSenderId: '21933192505',
    projectId: 'ctse-lab3',
    storageBucket: 'ctse-lab3.appspot.com',
    iosClientId: '21933192505-l9mdhcko0ivtmk4rp4ein2j4kmbb71aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseLab3',
  );
}
